import {useEffect,useRef,useState} from 'react';
import {Command,Search,X,Activity,BookOpen,ShieldCheck,ChevronRight,Link,Check} from 'lucide-react';
const navigate=(tab:string)=>document.querySelector<HTMLButtonElement>(`nav [data-tab="${tab}"]`)?.click();
export function ResearchCommand(){
 const dialog=useRef<HTMLDialogElement>(null);const [query,setQuery]=useState('');
 const actions=[{label:'Patient overview',tab:'Overview',icon:Activity},{label:'Research evidence',tab:'Validation',icon:ShieldCheck},{label:'Methodology',tab:'Methodology',icon:BookOpen}];
 const matches=actions.filter(a=>a.label.toLowerCase().includes(query.toLowerCase()));
 function open(){setQuery('');dialog.current?.showModal();}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();dialog.current?.open?dialog.current.close():open();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 return <><button className="research-search" onClick={open}><Command size={15}/><span>Quick find</span><kbd>⌘ K</kbd></button><dialog ref={dialog} className="research-command" aria-label="Quick navigation" onClick={e=>{if(e.target===e.currentTarget)e.currentTarget.close()}}><div className="command-input"><Search size={19}/><input aria-label="Search research sections" placeholder="Where would you like to go?" value={query} onChange={e=>setQuery(e.target.value)} autoFocus onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();dialog.current?.querySelector<HTMLButtonElement>('.command-result')?.focus()}if(e.key==='Enter'&&matches[0]){dialog.current?.close();navigate(matches[0].tab)}}}/><button aria-label="Close quick navigation" onClick={()=>dialog.current?.close()}><X size={18}/></button></div><div className="command-results">{matches.map(({label,tab,icon:Icon})=><button className="command-result" key={tab} onClick={()=>{dialog.current?.close();navigate(tab)}}><Icon size={18}/>{label}<ChevronRight size={16}/></button>)}{!matches.length&&<p>No matching sections. Try “overview” or “evidence”.</p>}</div><small>Use Tab to browse · Enter to select · Esc to close</small></dialog></>;
}
export function SessionTimeline({minute,onScene}:{minute:number;onScene:(minute:number)=>void}){
 return <section className="research-timeline"><h2>A session, in three moments.</h2><p>Explore the illustrative replay from baseline to recovery.</p><ol>{[[32,'10:32','A quiet baseline','Clean signals give the comparison context.'],[45,'10:45','Movement changes confidence','The demo withholds the score during motion.'],[60,'11:00','The signal returns','Explore recovery after the artifact.']].map(([t,time,title,description])=><li key={t}><button aria-pressed={minute===t} onClick={()=>onScene(Number(t))}><time>{time}</time><span className="timeline-dot"><Activity size={14}/></span><span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={17}/></button></li>)}</ol></section>;
}
export function ResearchAccordion(){
 const [opened,setOpened]=useState<string|null>(null),[copied,setCopied]=useState('');
 const rows=[['data-boundary','What is real, and what is illustrative?','HbA1c labels come from 16 public research participants. Wearable signals, similarity scores, and motion intervals are synthetic demo fixtures.'],['confidence-boundary','Why can a score disappear?','The replay suppresses similarity scores during low-quality windows. Movement can corrupt optical signals; the confidence gate keeps this limitation visible.'],['patient-boundary','Does patient view protect real records?','Patient view displays assigned demo participant 004. It is a presentation switch. Real patient records require authentication and server-side authorization.'],['validation-boundary','Is this clinically validated?','No. Classifier training, held-out evaluation, and independent CGM validation remain pending. PulseCast is a research prototype, not a diagnostic tool.']];
 useEffect(()=>{const update=()=>{const id=new URLSearchParams(location.hash.split('?')[1]).get('section');if(id&&rows.some(r=>r[0]===id)){setOpened(id);setTimeout(()=>document.getElementById(id)?.scrollIntoView({block:'center'}),0)}};update();window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[]);
 return <section className="research-faq"><h2>Good questions. Clear boundaries.</h2><p>Understand the evidence behind the experience.</p><div>{rows.map(([id,title,text])=><article id={id} key={id}><h3><button id={`${id}-trigger`} aria-expanded={opened===id} aria-controls={`${id}-answer`} onClick={()=>setOpened(opened===id?null:id)}><ChevronRight className={opened===id?'expanded':''} size={17}/>{title}</button><button aria-label={`Copy link: ${title}`} onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}${location.pathname}#/methodology?section=${id}`);setCopied(id);setTimeout(()=>setCopied(''),2000)}catch{location.hash=`/methodology?section=${id}`;setOpened(id)}}}>{copied===id?<Check size={16}/>:<Link size={16}/>}</button></h3><div id={`${id}-answer`} role="region" aria-labelledby={`${id}-trigger`} hidden={opened!==id}><p>{text}</p></div></article>)}</div><span className="sr-only" aria-live="polite">{copied?'Link copied':''}</span></section>;
}
