import './care-earth.css';
// Public pharmacy directory only. There is no inventory feed or patient location tracking.
const pharmacies=[
 {name:'NC State Campus Health Pharmacy',address:'2815 Cates Avenue',phone:'9195155040',coords:[-78.6757,35.7838],source:'https://healthypack.dasa.ncsu.edu/services-provided/pharmacy/'},
 {name:'CVS · Hillsborough Street',address:'3001 Hillsborough Street, Suite 100',phone:'9198396393',coords:[-78.6774,35.7895],source:'https://www.cvs.com/store-locator/raleigh-nc-pharmacies/3001-hillsborough-st%2C-suite-100-raleigh-nc-27607/storeid%3D10682'}
];
export function mountCareEarth(){
 const section=document.createElement('section');section.className='care-earth loading';section.id='care-earth';
 section.innerHTML=`<div class="earth-imagery-credit">Imagery © Esri, Maxar, Earthstar Geographics / GIS community</div><div class="cosmos-3d" aria-label="Live 3D Earth with clouds, atmosphere, stars and sunlight"></div><div class="cosmos-stars" aria-hidden="true"></div><div class="care-map" aria-label="Interactive globe flying to NC State and nearby pharmacies"></div><div class="care-heading"><span>PULSECAST / CARE EXPLORER</span><h1>A world of care.<br>Closer than you think.</h1><p class="flight-status" role="status">From the cosmos to your campus.</p><div class="care-actions"><button class="skip-flight">Find campus pharmacies ↗</button><button class="replay-flight">Replay journey</button></div></div><div class="pharmacy-panel" hidden><span>NC STATE · RALEIGH</span><h2>Find a pharmacy.<br>Confirm your insulin.</h2><label>Medication to ask about<select class="insulin-choice"><option>Rapid-acting insulin</option><option>Insulin lispro</option><option>Insulin aspart</option><option>Insulin glulisine</option></select></label><p class="stock-note">Stock unknown. Call to confirm the exact product, formulation, prescription requirements, and pickup availability.</p><div class="pharmacy-results">${pharmacies.map((p,i)=>`<article><button class="focus-pharmacy" data-index="${i}">${p.name} ↗</button><p>${p.address}</p><span class="unknown-stock">Availability not verified</span><div><a href="tel:+1${p.phone}">Call pharmacy</a><a href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p.address+', Raleigh NC')}&travelmode=walking" target="_blank" rel="noreferrer">Directions ↗</a><a href="${p.source}" target="_blank" rel="noreferrer">Source</a></div></article>`).join('')}</div><a class="more-pharmacies" href="https://www.google.com/maps/search/pharmacies+near+NC+State+University+Raleigh/" target="_blank" rel="noreferrer">Search more pharmacies in Google Maps ↗</a><a class="earth-link" href="https://earth.google.com/web/search/North+Carolina+State+University/" target="_blank" rel="noreferrer">Open NC State in Google Earth ↗</a><small>Earth textures: Solar System Scope / INOVE (CC BY 4.0). Satellite imagery: Esri, Maxar, Earthstar Geographics and GIS community · Public directory, not live inventory. Pin positions approximate.</small></div>`;
 let flight,started=false,active=false;const status=section.querySelector('.flight-status');
 const reveal=()=>{section.classList.add('arrived');section.querySelector('.pharmacy-panel').hidden=false;status.textContent='NC State University · nearby pharmacy contacts';};
 const journey=()=>{if(!flight)return;section.classList.remove('arrived','descending');section.querySelector('.pharmacy-panel').hidden=true;status.textContent='From the cosmos to your campus.';flight.play();};
 const focus=i=>{const p=pharmacies[i];flight?.focus(p.coords[1],p.coords[0]);section.querySelectorAll('article').forEach((el,j)=>el.classList.toggle('selected',i===j));};
 const boot=async()=>{if(started)return;started=true;try{const {createCosmosFlight}=await import('./cosmos-flight.js');flight=await createCosmosFlight(section.querySelector('.cosmos-3d'),p=>{section.classList.toggle('descending',p>.35);status.textContent=p<.5?'Approaching North America…':p<.85?'Descending toward Raleigh…':'Arriving at NC State University…';},reveal);section.classList.remove('loading');if(location.hash==='#/care')journey();}catch{section.classList.remove('loading');status.textContent='Satellite view unavailable. Pharmacy contacts remain available.';reveal();}};
 section.querySelectorAll('.focus-pharmacy').forEach(button=>button.onclick=()=>focus(Number(button.dataset.index)));
 section.addEventListener('earth:pharmacy',e=>focus(e.detail));
 section.querySelector('.skip-flight').onclick=()=>{flight?.finish();};section.querySelector('.replay-flight').onclick=journey;
 const activate=()=>{const next=location.hash==='#/care';if(next&&!active){if(!started)boot();else if(flight)journey();}if(!next)flight?.stop();active=next;};
 window.addEventListener('hashchange',activate);new IntersectionObserver(entries=>{if(entries[0].isIntersecting)activate();}).observe(section);requestAnimationFrame(activate);return section;
}
