import * as THREE from 'three';
/** Live WebGL scene. Planet maps: Solar System Scope / INOVE, CC BY 4.0. */
export async function createCosmosFlight(host,onProgress,onComplete){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#020711');renderer.outputColorSpace=THREE.SRGBColorSpace;host.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.002,150);const loader=new THREE.TextureLoader();
 const textures=await Promise.all(['day','night','clouds'].map(name=>loader.loadAsync(`${import.meta.env.BASE_URL}textures/earth-${name}.jpg`)));textures.forEach(t=>{t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());});
 const light=new THREE.Vector3(.87,.112,.475).normalize();
 const sphere=new THREE.SphereGeometry(1,160,96);
 const earth=new THREE.Mesh(sphere,new THREE.ShaderMaterial({uniforms:{day:{value:textures[0]},night:{value:textures[1]},sun:{value:light}},vertexShader:`varying vec2 vUv;varying vec3 vNormal;void main(){vUv=uv;vNormal=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D day,night;uniform vec3 sun;varying vec2 vUv;varying vec3 vNormal;void main(){float d=dot(normalize(vNormal),sun);float lit=smoothstep(-.12,.25,d);vec3 surface=texture2D(day,vUv).rgb;vec3 cities=texture2D(night,vUv).rgb;vec3 col=surface*(.08+lit*.92)+cities*(1.-lit)*1.4;col+=vec3(.03,.035,.12)*(1.-lit);gl_FragColor=vec4(col,1.);}` }));scene.add(earth);
 scene.add(new THREE.AmbientLight(0x8599ff,.25));const sunlight=new THREE.DirectionalLight(0xffeee0,2.7);sunlight.position.copy(light.clone().multiplyScalar(5));scene.add(sunlight);
 const clouds=new THREE.Mesh(new THREE.SphereGeometry(1.008,128,80),new THREE.MeshPhongMaterial({map:textures[2],alphaMap:textures[2],transparent:true,opacity:.66,depthWrite:false,color:0xe5ebff}));scene.add(clouds);
 const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(1.035,128,80),new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,blending:THREE.AdditiveBlending,vertexShader:`varying vec3 n,v;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}`,fragmentShader:`varying vec3 n,v;void main(){float edge=pow(max(0.,1.-abs(dot(normalize(n),normalize(v)))),3.);gl_FragColor=vec4(vec3(.35,.42,1.)*edge,edge*.7);}`}));scene.add(atmosphere);
 const sky=new THREE.Mesh(new THREE.SphereGeometry(70,64,32),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,vertexShader:`varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 p;float hash(vec3 q){return fract(sin(dot(q,vec3(127.1,311.7,74.7)))*43758.5453);}float noise(vec3 q){vec3 i=floor(q),f=fract(q);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}void main(){vec3 d=normalize(p);float n=0.;float a=.5;vec3 q=d*4.;for(int i=0;i<5;i++){n+=noise(q)*a;q=q*2.1+4.;a*=.5;}float band=exp(-pow((d.y+d.x*.28)*3.,2.));vec3 col=mix(vec3(.025,.09,.16),vec3(.32,.13,.25),smoothstep(.35,.75,n));col*=pow(n,2.)*band*6.5;gl_FragColor=vec4(col+vec3(.003,.006,.018),1.);}`}));scene.add(sky);
 let seed=13579;const rand=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};const positions=[],colors=[];
 for(let i=0;i<18000;i++){const y=rand()*2-1,a=rand()*Math.PI*2,r=35+rand()*25;positions.push(Math.sqrt(1-y*y)*Math.cos(a)*r,y*r,Math.sqrt(1-y*y)*Math.sin(a)*r);const c=new THREE.Color().setHSL(.55+rand()*.45,.15+rand()*.4,.5+rand()*.45);colors.push(c.r,c.g,c.b);}
 const starsGeometry=new THREE.BufferGeometry();starsGeometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));starsGeometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const stars=new THREE.Points(starsGeometry,new THREE.PointsMaterial({size:.13,vertexColors:true,transparent:true,opacity:.9,sizeAttenuation:true,depthWrite:false}));scene.add(stars);
 const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=256;const ctx=glowCanvas.getContext('2d'),gradient=ctx.createRadialGradient(128,128,0,128,128,128);gradient.addColorStop(0,'#fff');gradient.addColorStop(.08,'#fff8de');gradient.addColorStop(.22,'#ffcfb1cc');gradient.addColorStop(.5,'#d47aa548');gradient.addColorStop(1,'#a5488000');ctx.fillStyle=gradient;ctx.fillRect(0,0,256,256);const flare=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(glowCanvas),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));flare.scale.set(2.3,2.3,1);scene.add(flare);
 const nebulaCanvas=document.createElement('canvas');nebulaCanvas.width=nebulaCanvas.height=512;const nc=nebulaCanvas.getContext('2d'),ng=nc.createRadialGradient(256,256,70,256,256,256);ng.addColorStop(0,'#edb8cd00');ng.addColorStop(.3,'#d899c08c');ng.addColorStop(.55,'#947daf55');ng.addColorStop(1,'#23446800');nc.fillStyle=ng;nc.fillRect(0,0,512,512);const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(nebulaCanvas),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));halo.scale.set(5.3,5.3,1);scene.add(halo);
 let frame=0,start=0,running=false;const duration=16000,reduced=matchMedia('(prefers-reduced-motion:reduce)');
 const geo=(lat,lon)=>{const phi=(90-lat)*Math.PI/180,theta=(lon+180)*Math.PI/180;return new THREE.Vector3(-Math.sin(phi)*Math.cos(theta),Math.cos(phi),Math.sin(phi)*Math.sin(theta));};
 const origin=geo(22,45),destination=geo(35.786,-78.6748),axis=new THREE.Vector3().crossVectors(origin,destination).normalize(),angle=origin.angleTo(destination);
 const resize=()=>{const box=host.getBoundingClientRect();if(!box.width||!box.height)return;renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(host);
 function draw(now){if(!running)return;const elapsed=now-start,p=Math.min(1,elapsed/duration);const travel=THREE.MathUtils.smoothstep(p,.16,.67);const direction=origin.clone().applyAxisAngle(axis,angle*travel);const dive=THREE.MathUtils.smoothstep(p,.28,.75);const distance=1.012+4.05*Math.pow(1-dive,2.4);camera.position.copy(direction.multiplyScalar(distance));camera.lookAt(0,0,0);halo.position.copy(origin.clone().multiplyScalar(-1.5));halo.material.opacity=1-travel;clouds.rotation.y=elapsed*.000002;stars.rotation.y=elapsed*.0000015;flare.position.copy(origin.clone().multiplyScalar(.1)).add(new THREE.Vector3(.81,.1,.81));flare.material.opacity=1-travel;renderer.render(scene,camera);host.style.opacity=String(1-THREE.MathUtils.smoothstep(p,.58,.78));onProgress(p);if(p<1)frame=requestAnimationFrame(draw);else{running=false;onComplete();}}
 const play=()=>{cancelAnimationFrame(frame);host.style.visibility='visible';host.style.opacity='1';start=performance.now();running=true;resize();if(reduced.matches){onProgress(1);host.style.opacity='0';running=false;onComplete();}else frame=requestAnimationFrame(draw);};
 const stop=()=>{running=false;cancelAnimationFrame(frame);host.style.opacity='0';};
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){stop();onProgress(1);onComplete();}});return {play,stop};
}
