/** Cinematic introduction. Stock photography illustrates activity, not dataset participants. */
let retainedIntro,retainedEditorial;
export function mountExperience(){
 const app=document.querySelector('#app');
 if(retainedIntro){app.prepend(retainedIntro);app.querySelector('main').before(retainedEditorial);return;}
 const intro=document.createElement('section');intro.className='cinema';
 intro.innerHTML=`<div class="cinema-photo"></div><div class="cinema-shade"></div><div class="cinema-grain"></div><div class="cinema-content"><span class="film-label"><i></i> PULSECAST / HUMAN SIGNALS</span><h2>Every heartbeat.<br><em>A bigger picture.</em></h2><p>A window into the patterns beneath your everyday.<br>Wearable intelligence. Made human.</p><div class="hero-actions"><button id="enter-dashboard">Explore your signals <span>↗</span></button><button id="discover-science">Behind the science <span>↓</span></button></div><span class="hero-footnote">16 participants. Six wearable signals. One research experience.</span></div><div class="film-readout"><span>01 / THE HUMAN SIGNAL</span><div class="heartbeat-line"><svg viewBox="0 0 300 65"><path d="M0 35H65L76 30L86 41L97 9L109 60L120 35H183L196 30L207 39L217 15L230 53L241 35H300"/></svg></div><span>ILLUSTRATION / NOT LIVE TELEMETRY</span></div><button class="motion-toggle" aria-label="Pause background motion">Ⅱ Motion</button><a class="photo-credit" href="https://unsplash.com/photos/E9PdTVfEujI" target="_blank" rel="noreferrer">Photography / Greg Rosenke</a><div class="scroll-cue">SCROLL TO EXPLORE <span>↓</span></div>`;
 const video=document.createElement('video');video.className='cinema-video';video.muted=true;video.loop=true;video.playsInline=true;video.preload='none';video.setAttribute('aria-hidden','true');intro.querySelector('.cinema-photo').after(video);
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 if(!reduced){video.src='https://videos.pexels.com/video-files/8484747/8484747-uhd_2560_1440_30fps.mp4';video.play().catch(()=>{});video.addEventListener('playing',()=>video.classList.add('loaded'));}
 const quality=document.createElement('button');quality.className='video-quality';quality.textContent='4K ↗';quality.setAttribute('aria-label','Play 4K background video');quality.onclick=()=>{video.src='https://videos.pexels.com/video-files/8484747/8484747-uhd_3840_2160_30fps.mp4';video.play().catch(()=>{});quality.textContent='4K SELECTED';};intro.append(quality);
 const credit=intro.querySelector('.photo-credit');credit.href='https://www.pexels.com/video/a-person-running-from-one-place-to-another-8484747/';credit.textContent='Film / Liliana Drew · Photo / Greg Rosenke';
 app.prepend(intro);
 const editorial=document.createElement('section');editorial.className='editorial';editorial.innerHTML=`<div class="editorial-intro"><span class="film-label">02 / UNDER THE SURFACE</span><h2>Your body has a rhythm.<br>Learn to read it.</h2><p>Movement. Recovery. Quiet moments. Explore how wearable signals come together to reveal a richer physiological profile.</p></div><div class="editorial-cards"><article class="story-card human"><div><span>01 / MOVEMENT</span><h3>Life in motion.</h3><p>Acceleration gives every heartbeat context. Know when movement changes the signal.</p></div></article><article class="story-card signal-story"><div class="orbital"><i></i><i></i><i></i><span>⌁</span></div><div><span>02 / PHYSIOLOGY</span><h3>More than a number.</h3><p>Heart rate, variability, temperature and EDA. A connected view of your signals.</p></div></article><article class="story-card evidence-story"><div class="evidence-number">16<span>human stories</span></div><div><span>03 / RESEARCH</span><h3>Evidence comes first.</h3><p>Observed HbA1c labels. Independent glucose validation. Transparent demo boundaries.</p></div></article></div><div class="dashboard-intro"><span class="film-label">03 / THE EXPLORER</span><h2>Meet the signals.</h2><p>An interactive research workspace. Choose a participant and replay a physiological profile.</p></div>`;
 app.querySelector('main').before(editorial);
 document.querySelector('#enter-dashboard').onclick=()=>document.querySelector('main').scrollIntoView({behavior:'smooth'});
 document.querySelector('#discover-science').onclick=()=>editorial.scrollIntoView({behavior:'smooth'});
 const motion=document.querySelector('.motion-toggle');motion.onclick=()=>{const paused=intro.classList.toggle('motion-paused');if(paused)video.pause();else {if(!video.src)video.src='https://videos.pexels.com/video-files/8484747/8484747-uhd_2560_1440_30fps.mp4';video.play().catch(()=>{});}motion.textContent=paused?'▶ Motion':'Ⅱ Motion';motion.setAttribute('aria-label',paused?'Resume background motion':'Pause background motion')};
 const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.1});editorial.querySelectorAll('.story-card,.editorial-intro,.dashboard-intro').forEach(el=>observer.observe(el));
 retainedIntro=intro;retainedEditorial=editorial;
}
