import icon0 from '../../node_modules/@tabler/icons/icons/outline/arrow-up-right.svg?raw';
import icon1 from '../../node_modules/@tabler/icons/icons/outline/player-play.svg?raw';
import icon2 from '../../node_modules/@tabler/icons/icons/outline/stethoscope.svg?raw';
import icon3 from '../../node_modules/@tabler/icons/icons/outline/heart.svg?raw';
import icon4 from '../../node_modules/@tabler/icons/icons/outline/sun.svg?raw';
import icon5 from '../../node_modules/@tabler/icons/icons/outline/moon.svg?raw';
import icon6 from '../../node_modules/@tabler/icons/icons/outline/circle-check.svg?raw';
import icon7 from '../../node_modules/@tabler/icons/icons/outline/wave-sine.svg?raw';
import icon8 from '../../node_modules/@tabler/icons/icons/outline/shield-check.svg?raw';
import icon9 from '../../node_modules/@tabler/icons/icons/outline/sparkles.svg?raw';
const icons = {'arrow-up-right':icon0,'player-play':icon1,'stethoscope':icon2,'heart':icon3,'sun':icon4,'moon':icon5,'circle-check':icon6,'wave-sine':icon7,'shield-check':icon8,'sparkles':icon9};
export function mountIcons(root=document){root.querySelectorAll("i.ti").forEach(element=>{const name=[...element.classList].find(value=>value.startsWith("ti-"))?.slice(3);element.innerHTML=icons[name]||"";});}
