import {cohort, point} from '../data/cohort.js';
let connection='checking',storyObserver;
const api=import.meta.env.VITE_API_URL||(location.hostname==='localhost'?'/api':'');
if(api)fetch(`${api.replace(/\/$/,'')}/health`,{signal:AbortSignal.timeout(65000)}).then(r=>r.ok?r.json():Promise.reject()).then(r=>{connection=r.llm_configured?'ready':'offline';refreshStatus();}).catch(()=>{connection='offline';refreshStatus();});else connection='offline';
function refreshStatus(){document.querySelectorAll('.connection-status').forEach(el=>{el.dataset.status=connection;el.textContent=connection==='ready'?'Assistant connected':connection==='checking'?'Connecting assistant':'Assistant unavailable';});}
/** Extra demo interactions use the same synthetic replay as the core dashboard. */
export function mountStudio({audience,participant,minute,onScene}){
 storyObserver?.disconnect();
 const main=document.querySelector('main');main.id='workspace';
 const brand=document.querySelector('.brand');brand.href='#home';brand.innerHTML='<span class="brand-mark"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14" stroke-width="3.5"/></svg></span>PulseCast<span class="brand-dot">.</span>';
 const status=document.querySelector('.header-right');status.innerHTML='<span class="connection-status"></span><span class="prototype-tag">RESEARCH EDITION</span>';refreshStatus();
 const theme=document.querySelector('.theme-toggle');theme.title='Change appearance';
 document.querySelector('.notice div strong').textContent='Evidence, with context.';
 const overview=!!document.querySelector('#play');
 if(overview){
  const p=point(participant,minute),baseline=point(participant,0),profile=cohort.find(p=>p.id===participant);
  const journey=document.createElement('section');journey.className='demo-journey';journey.innerHTML=`<div class="journey-heading"><div><span class="section-kicker">THE 60-SECOND DEMO</span><h2>Three moments. A different perspective.</h2></div><span class="demo-badge">INTERACTIVE REPLAY</span></div><div class="journey-scenes">${[[32,'01','A quiet baseline','See clean signals in context.','baseline'],[45,'02','When movement matters','Watch the confidence gate respond.','motion'],[60,'03','The signal returns','Resume the profile after the artifact.','recovery']].map(([t,n,h,d,c])=>`<button data-scene="${t}" class="scene ${c} ${minute===t?'selected':''}" aria-pressed="${minute===t}"><span class="scene-symbol">${c==='baseline'?'⌁':c==='motion'?'≋':'↗'}</span><div><span class="scene-number">${n} / ${10+Math.floor(t/60)}:${String(t%60).padStart(2,'0')}</span><strong>${h}</strong><small>${d}</small></div><span class="scene-arrow">↗</span></button>`).join('')}</div>`;
  document.querySelector('.metrics').before(journey);journey.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>onScene(+b.dataset.scene));
  const trend=document.querySelector('.trend');trend.classList.add('studio-trend');trend.querySelector('.legend').innerHTML='<i></i> Illustrative similarity';
  const svg=trend.querySelector('svg');const ns='http://www.w3.org/2000/svg';const rect=document.createElementNS(ns,'rect');rect.setAttribute('x',48+42/90*820);rect.setAttribute('y','25');rect.setAttribute('width',7/90*820);rect.setAttribute('height','180');rect.setAttribute('class','artifact-band');svg.querySelector('defs').after(rect);
  const note=document.createElement('div');note.className='chart-evidence';note.innerHTML='<span><i></i> Motion artifact window / 10:42-10:48</span><span>Score is suppressed in low-quality windows</span>';trend.querySelector('.replay').before(note);
  const metrics=document.querySelectorAll('.metrics .card');metrics[0].querySelector('.eyebrow').innerHTML='RESEARCH SIMILARITY <span>↗</span>';metrics[1].querySelector('.eyebrow').textContent='WINDOW CHANGE';metrics[2].querySelector('.eyebrow').textContent='CONFIDENCE GATE';
  if(p.quality<50){metrics[2].classList.add('quality-warning');metrics[0].classList.add('suppressed');}
  const insights=document.createElement('section');insights.className='studio-insights';
  insights.innerHTML=`<article class="card baseline-card"><div class="section-head"><div><span class="section-kicker">PERSONAL CONTEXT</span><h2>A baseline. A better question.</h2></div><span class="round-icon">↗</span></div><p>Compare the current window with the start of this illustrative session.</p><div class="baseline-rows">${[['Heart rate',baseline.hr,p.hr,'bpm'],['HRV · RMSSD',baseline.hrv,p.hrv,'ms'],['Skin temperature',baseline.temp,p.temp,'°C']].map(([name,b,c,u])=>`<div><span>${name}</span><div class="baseline-meter"><i style="width:${Math.min(94,c/(b*1.3)*100)}%"></i><b style="left:77%"></b></div><strong>${c} <small>${u}</small></strong><em>${c-b>=0?'+':''}${(c-b).toFixed(u==='°C'?1:0)}</em></div>`).join('')}</div><div class="baseline-legend"><span><i></i> Current window</span><span><b></b> Session start</span><span>Synthetic comparison</span></div></article><article class="card confidence-card"><div class="section-head"><div><span class="section-kicker">TRUST THE CONTEXT</span><h2>${p.quality<50?'A useful answer can be “wait.”':'Confidence you can inspect.'}</h2></div><span class="quality-indicator ${p.quality<50?'warning':''}">${p.quality<50?'GATED':'CLEAR'}</span></div><div class="confidence-visual"><svg viewBox="0 0 150 150" role="img" aria-label="Illustrative signal quality ${p.quality} percent"><circle cx="75" cy="75" r="57" class="ring-track"/><circle cx="75" cy="75" r="57" class="ring-value ${p.quality<50?'warning':''}" stroke-dasharray="${p.quality/100*358} 358"/><text x="75" y="79" class="ring-number">${p.quality}%</text><text x="75" y="99" class="ring-label">SIGNAL QUALITY</text></svg><div><strong>${p.quality<50?'Motion detected. Score withheld.':'Clean window. Context retained.'}</strong><p>${p.quality<50?'The demo suppresses the research score during the simulated movement interval. Explore recovery to see it return.':'Accelerometer context helps distinguish a useful physiological window from a motion-corrupted one.'}</p></div></div><div class="quality-timeline" aria-label="Session quality timeline">${Array.from({length:46},(_,i)=>`<i class="${i*2>=42&&i*2<=48?'artifact':''} ${i*2>minute?'future':''}" title="Minute ${i*2}: ${i*2>=42&&i*2<=48?'simulated artifact':'simulated clean signal'}"></i>`).join('')}</div><div class="quality-caption"><span>10:00</span><span>Illustrative quality timeline</span><span>11:30</span></div></article>`;
  document.querySelector('.clinical-charts').before(insights);
  const intelligence=document.createElement('div');intelligence.className='intelligence-label';intelligence.innerHTML='<span class="section-kicker">THE PHYSIOLOGY LAYER</span><h2>One session. Multiple perspectives.</h2><p>Four signals, synchronized to the same replay window.</p>';document.querySelector('.clinical-charts').before(intelligence);
  const assistant=document.querySelector('.explain');assistant.querySelector('.assistant-copy').textContent='From signal to explanation. Ask a question grounded in this demo profile.';assistant.querySelector('.star')?.remove();assistant.querySelector('h2').innerHTML='<span class="assistant-orb"><i class="ti ti-sparkles" aria-hidden="true"></i></span> PulseCast Assistant';
  const actionbar=document.createElement('section');actionbar.className='session-actions';actionbar.innerHTML='<div><span class="section-kicker">TAKE THE EVIDENCE WITH YOU</span><strong>Your session, with its context.</strong><p>Export the displayed values, provenance, and demo limitations.</p></div><button class="export-session">Download session brief <span>↓</span></button>';document.querySelector('.two-col.lower').after(actionbar);
  actionbar.querySelector('button').onclick=()=>{const report={project:'PulseCast',research_demo:true,participant,audience,minute,observed_hba1c:profile.a1c,hba1c_source:'PhysioNet BIG IDEAs Glycemic Variability and Wearable Device Data v1.1.3 demographics',wearable_data:'synthetic illustrative replay',trained_model:false,diagnostic_use:false,displayed_signals:p,comparison_baseline:baseline,score_suppressed:p.quality<50,glucose_validation:'not imported',generated_at:new Date().toISOString()};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=`pulsecast-session-${participant}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 }
 const story=document.createElement('section');story.className='product-story';story.innerHTML=`<div class="story-heading"><h2>More perspective. Less guesswork.</h2><p>A research experience built around the questions that matter.</p></div><div class="product-bento"><article class="bento-evidence"><h3>Every insight. With its receipts.</h3><div class="evidence-stack"><div><span class="evidence-icon"><i class="ti ti-circle-check" aria-hidden="true"></i></span><div><strong>Observed labels</strong><small>16 public research participants</small></div><span class="evidence-state">Public data</span></div><div><span class="evidence-icon"><i class="ti ti-wave-sine" aria-hidden="true"></i></span><div><strong>Wearable replay</strong><small>Illustrative signals and scores</small></div><span class="evidence-state">Synthetic</span></div><div><span class="evidence-icon"><i class="ti ti-shield-check" aria-hidden="true"></i></span><div><strong>Independent validation</strong><small>CGM import and evaluation pending</small></div><span class="evidence-state">Pending</span></div></div><button class="open-evidence">Explore the evidence <i class="ti ti-arrow-up-right" aria-hidden="true"></i></button></article><article class="bento-human"><figure><img src="https://images.pexels.com/photos/7579831/pexels-photo-7579831.jpeg?auto=compress&cs=tinysrgb&w=1920" width="1920" height="1280" alt="Doctor and patient in a consultation; illustrative stock photography" loading="lazy"><figcaption><a href="https://www.pexels.com/photo/a-doctor-talking-the-patient-7579831/" target="_blank" rel="noreferrer">Photography by cottonbro studio / Pexels</a></figcaption></figure><div><h3>Clinical perspective. Personal understanding.</h3><p>Two thoughtfully different views. One shared story.</p><small>Demo view switching is presentation only, not authenticated patient access.</small></div></article></div>`;
 document.querySelector('.content footer').before(story);
 story.querySelector('.open-evidence').onclick=()=>openEvidence(audience);
 const observer=storyObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.08});story.querySelectorAll('.product-bento article,.story-heading').forEach(el=>observer.observe(el));

 document.querySelector('footer').innerHTML='<span>PulseCast © 2026 · Built at WolfHacks</span><span>Research prototype. Not for clinical use.</span>';
}
function openEvidence(audience){
 const dialog=document.createElement('dialog');dialog.className='evidence-dialog';dialog.innerHTML=`<button class="close-dialog" aria-label="Close evidence details">×</button><span class="section-kicker">THE EVIDENCE TRAIL</span><h2>Clarity is a feature.</h2><p>This interface separates observed research data from illustrative behavior.</p><dl><dt>Observed</dt><dd>HbA1c labels for 16 participants, sourced from public PhysioNet demographics.</dd><dt>Illustrative</dt><dd>All displayed wearable signals, similarity scores, baseline changes, and the motion-artifact interval are synthetic demo fixtures.</dd><dt>Connected</dt><dd>PulseCast Assistant generates explanations through the hosted backend using the demo participant context.</dd><dt>Pending</dt><dd>Trained classifier evaluation, calibrated probabilities, raw-signal quality validation, and independent CGM analysis.</dd><dt>Access</dt><dd>${audience==='patient'?'Patient view shows assigned demo participant 004.':'Doctor view explores the public research cohort.'} The view switch is presentation only; real patient records require authentication and server-side permissions.</dd></dl><a href="https://physionet.org/content/big-ideas-glycemic-wearable/1.1.3/" target="_blank" rel="noreferrer">Read the source dataset ↗</a>`;document.body.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
}
